CREATE TABLE department (
    name	VARCHAR(512),
    faculty_name	VARCHAR(512),
    code	VARCHAR(512)
);

INSERT INTO department (name, faculty_name, code) VALUES ('Computer Science', 'Computing and Informaticcs', 'CSE');
INSERT INTO department (name, faculty_name, code) VALUES ('Cyber Security Science', 'Computing and Informaticcs', 'CYB');
INSERT INTO department (name, faculty_name, code) VALUES ('Information Systems', 'Computing and Informaticcs', 'ISS');
INSERT INTO department (name, faculty_name, code) VALUES ('Library and Information Science', 'Computing and Informaticcs', 'LIS');
INSERT INTO department (name, faculty_name, code) VALUES ('Agricultural Engineering', 'Engineering and Technology', 'AGE');
INSERT INTO department (name, faculty_name, code) VALUES ('Chemical Engineering', 'Engineering and Technology', 'CHE');
INSERT INTO department (name, faculty_name, code) VALUES ('Civil Engineering', 'Engineering and Technology', 'CVE');
INSERT INTO department (name, faculty_name, code) VALUES ('Computer Engineering', 'Engineering and Technology', 'CPE');
INSERT INTO department (name, faculty_name, code) VALUES ('Electronic and Electrical Engineering', 'Engineering and Technology', 'EEE');
INSERT INTO department (name, faculty_name, code) VALUES ('Food Engineering ', 'Engineering and Technology', 'FDE');
INSERT INTO department (name, faculty_name, code) VALUES ('Mechanical Engeering', 'Engineering and Technology', 'MEE');
INSERT INTO department (name, faculty_name, code) VALUES ('Earth Science', 'Pure and Applied Sciences', 'ESC');
INSERT INTO department (name, faculty_name, code) VALUES ('General Studies', 'Pure and Applied Sciences', 'GNS');
INSERT INTO department (name, faculty_name, code) VALUES ('Pure and Applied Biology', 'Pure and Applied Sciences', 'PAB');
INSERT INTO department (name, faculty_name, code) VALUES ('Pure and Applied Chemistry', 'Pure and Applied Sciences', 'PAC');
INSERT INTO department (name, faculty_name, code) VALUES ('Pure and Applied Mathematics', 'Pure and Applied Sciences', 'APM');
INSERT INTO department (name, faculty_name, code) VALUES ('Pure and Applied Physics', 'Pure and Applied Sciences', 'PAP');
INSERT INTO department (name, faculty_name, code) VALUES ('Science Laboratory Technology', 'Pure and Applied Sciences', 'SLT');
INSERT INTO department (name, faculty_name, code) VALUES ('Statistics', 'Pure and Applied Sciences', 'STS');
INSERT INTO department (name, faculty_name, code) VALUES ('English and Literary Studies', 'Arts and Social Sciences', 'ELS');
INSERT INTO department (name, faculty_name, code) VALUES ('Philosophy', 'Arts and Social Sciences', 'PHY');
INSERT INTO department (name, faculty_name, code) VALUES ('History ', 'Arts and Social Sciences', 'HST');
INSERT INTO department (name, faculty_name, code) VALUES ('Sociology', 'Arts and Social Sciences', 'SOC');
INSERT INTO department (name, faculty_name, code) VALUES ('Accounting', 'Management Sciences', 'ACC');
INSERT INTO department (name, faculty_name, code) VALUES ('Business Management', 'Management Sciences', 'BMT');
INSERT INTO department (name, faculty_name, code) VALUES ('Economics', 'Management Sciences', 'ECO');
INSERT INTO department (name, faculty_name, code) VALUES ('Marketing', 'Management Sciences', 'MKT');
INSERT INTO department (name, faculty_name, code) VALUES ('Transport Management', 'Management Sciences', 'TMT');
INSERT INTO department (name, faculty_name, code) VALUES ('Architecture', 'Management Sciences', 'ART');
INSERT INTO department (name, faculty_name, code) VALUES ('Building', 'Environmental Sciences', 'BUG');
INSERT INTO department (name, faculty_name, code) VALUES ('Estate Management', 'Environmental Sciences', 'EMT');
INSERT INTO department (name, faculty_name, code) VALUES ('Fine and Applied Arts', 'Environmental Sciences', 'FAA');
INSERT INTO department (name, faculty_name, code) VALUES ('Surveying and Geoinformatic', 'Environmental Sciences', 'SUG');
INSERT INTO department (name, faculty_name, code) VALUES ('Urban and Regional Planning', 'Environmental Sciences', 'URP');
INSERT INTO department (name, faculty_name, code) VALUES ('Mental Health', 'Nursing Sciences', 'MNH');
INSERT INTO department (name, faculty_name, code) VALUES ('Medical/Surgical Nursing', 'Nursing Sciences', 'MSN');
INSERT INTO department (name, faculty_name, code) VALUES ('Maternal and Child Health Nursing', 'Nursing Sciences', 'MCN');
INSERT INTO department (name, faculty_name, code) VALUES ('Public Health Nursing', 'Nursing Sciences', 'PHN');
INSERT INTO department (name, faculty_name, code) VALUES ('Anaesthesia', 'Clinical Sciences', 'ANA');
INSERT INTO department (name, faculty_name, code) VALUES ('Community Medicine', 'Clinical Sciences', 'CME');
INSERT INTO department (name, faculty_name, code) VALUES ('Ear, Nose and Throat', 'Clinical Sciences', 'EAT');
INSERT INTO department (name, faculty_name, code) VALUES ('Medicine', 'Clinical Sciences', 'MED');
INSERT INTO department (name, faculty_name, code) VALUES ('Obsterics and Gynaecology', 'Clinical Sciences', 'OBG');
INSERT INTO department (name, faculty_name, code) VALUES ('Ophthalmology', 'Clinical Sciences', 'OPH');
INSERT INTO department (name, faculty_name, code) VALUES ('Pediatrics and Child Health', 'Clinical Sciences', 'PCH');
INSERT INTO department (name, faculty_name, code) VALUES ('Psychiatry', 'Clinical Sciences', 'PSY');
INSERT INTO department (name, faculty_name, code) VALUES ('Radiology', 'Clinical Sciences', 'RAD');
INSERT INTO department (name, faculty_name, code) VALUES ('Surgery', 'Clinical Sciences', 'SUY');
INSERT INTO department (name, faculty_name, code) VALUES ('Chemical Pathology', 'Basic Clinical Sciences', 'CHP');
INSERT INTO department (name, faculty_name, code) VALUES ('Haematology and Blood Transfusion', 'Basic Clinical Sciences', 'HBT');
INSERT INTO department (name, faculty_name, code) VALUES ('Medical Microbiology and Parasitology', 'Basic Clinical Sciences', 'MMP');
INSERT INTO department (name, faculty_name, code) VALUES ('Morbid Anatomy and Histopathology', 'Basic Clinical Sciences', 'MAH');
INSERT INTO department (name, faculty_name, code) VALUES ('Pharmacology and Therapeutics', 'Basic Clinical Sciences', 'PAT');
INSERT INTO department (name, faculty_name, code) VALUES ('Anatomy', 'Health Sciences', 'ANA');
INSERT INTO department (name, faculty_name, code) VALUES ('Biochemistry', 'Health Sciences', 'BCH');
INSERT INTO department (name, faculty_name, code) VALUES ('Medical Laboratory Science', 'Health Sciences', 'MLS');
INSERT INTO department (name, faculty_name, code) VALUES ('Physiology', 'Health Sciences', 'PSG');
INSERT INTO department (name, faculty_name, code) VALUES ('Agricultural Economics', 'Agricultural Sciences', 'AGC');
INSERT INTO department (name, faculty_name, code) VALUES ('Agricultural extension and Rural Development', 'Agricultural Sciences', 'AER');
INSERT INTO department (name, faculty_name, code) VALUES ('Animal Nutrition and Biotechnology', 'Agricultural Sciences', 'ANB');
INSERT INTO department (name, faculty_name, code) VALUES ('Animal Productin and Health', 'Agricultural Sciences', 'APH');
INSERT INTO department (name, faculty_name, code) VALUES ('Crop and Environmental Protection', 'Agricultural Sciences', 'CEP');
INSERT INTO department (name, faculty_name, code) VALUES ('Crop Production and Soil Science', 'Agricultural Sciences', 'CPS');
INSERT INTO department (name, faculty_name, code) VALUES ('Forest Resource Management', 'Renewable Natural Resources', 'FRM');
INSERT INTO department (name, faculty_name, code) VALUES ('Wildlife and Ecotourism Managemnt', 'Renewable Natural Resources', 'WEM');
INSERT INTO department (name, faculty_name, code) VALUES ('Aquaculture and Fisheries Management', 'Renewable Natural Resources', 'AFM');
