apiVersion: v1
kind: Namespace
metadata:
  name: study-earn

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: study-earn
type: Opaque
data:
  username: Y29kZXNwYWNl==
  password: cG9zdGdyZXM='

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
  namespace: study-earn
data:
  init.sql: |
    $(cat /path/to/your/init.sql)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: study-earn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: study-earn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: initdb
        configMap:
          name: postgres-initdb-config

